#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
export PATH="${HERE}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${HERE}/usr/lib:${LD_LIBRARY_PATH}"
export QT_PLUGIN_PATH="${HERE}/usr/lib/qt/plugins"
export QML2_IMPORT_PATH="${HERE}/usr/lib/qml"
export QT_QPA_PLATFORM_PLUGIN_PATH="${HERE}/usr/lib/qt/plugins/platforms"

# Try to autodetect the platform
if [ -n "$WAYLAND_DISPLAY" ]; then
    export QT_QPA_PLATFORM=wayland
else
    export QT_QPA_PLATFORM=xcb
fi

# Allow forcing a specific platform
if [ -n "$QT_QPA_PLATFORM" ]; then
    echo "Using Qt platform: $QT_QPA_PLATFORM"
fi

exec "${HERE}/usr/bin/coretrace-qt" "$@"
